@echo off
echo Starting all services...
docker-compose up -d

echo Waiting for services to be ready...
timeout /t 10

echo Starting producer...
start cmd /k "docker-compose up producer"

echo Starting console consumer...
docker-compose up kafka-console-consumer

echo Stopping all containers...
docker-compose down 